# Generated by Django 6.0.4 on 2026-04-18 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_medicineschedule_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineschedule',
            name='escalation_call_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicineschedule',
            name='escalation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineschedule',
            name='patient_call_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicineschedule',
            name='patient_call_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='medicineschedule',
            name='patient_last_call_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(auto_now_add=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('call_kind', models.CharField(choices=[('patient', 'Patient'), ('escalation', 'Escalation')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ringing', 'Ringing'), ('answered', 'Answered'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed'), ('completed', 'Completed'), ('taken', 'Taken'), ('missed', 'Missed'), ('escalated', 'Escalated')], default='queued', max_length=20)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('call_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='users.medicineschedule')),
            ],
        ),
    ]
