# Generated by Django 6.0.4 on 2026-04-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_last_logout_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='relative',
            name='conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='relative',
            name='phone_number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
